version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"  #11am utc
    timezone: "GMT"
  open-pull-requests-limit: 10
- package-ecosystem: gitsubmodule
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"  #11am utc
    timezone: "GMT"
  open-pull-requests-limit: 1
- package-ecosystem: gradle
  directory: "/java-dependencies/beta"
  schedule:
    interval: daily
    time: "11:00"  #11am utc
    timezone: "GMT"
  open-pull-requests-limit: 10
- package-ecosystem: gradle
  directory: "/java-dependencies/preview"
  schedule:
    interval: daily
    time: "11:00"  #11am utc
    timezone: "GMT"
  open-pull-requests-limit: 10
- package-ecosystem: gradle
  directory: "/java-dependencies/v1"
  schedule:
    interval: daily
    time: "11:00"  #11am utc
    timezone: "GMT"
  open-pull-requests-limit: 10
- package-ecosystem: gomod
  directory: "/GoV1Tests/goDependencies"
  schedule:
    interval: daily
    time: "11:00"  #11am utc
    timezone: "GMT"
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/TypeScriptV1Tests/TsDependecies"
  schedule:
    interval: daily
    time: "11:00"  #11am utc
    timezone: "GMT"
  open-pull-requests-limit: 10
