steps:
  - pwsh: |
      if (Test-Path $(Build.SourcesDirectory)/msgraph-sdk-raptor) # multi repo checkout
      {
        $scriptPath = $(Build.SourcesDirectory)/msgraph-sdk-raptor/scripts/transformAppSettings.ps1
      }
      else # single repo checkout
      {
        $scriptPath = $(Build.SourcesDirectory)/scripts/transformAppSettings.ps1
      }
      . $scriptPath -TenantID $(TenantID) -ClientID $(ClientID) -ClientSecret $(ClientSecret) -Authority $(Authority) -Username $(Username) -Password $(Password) -RaptorStorageConnectionString "$(RaptorStorageConnectionString)" -EducationClientId "$(EducationClientId)" -EducationTenantId "$(EducationTenantId)"
    displayName: 'Transform app settings with the secrets'

  - pwsh: |
      Get-Content $env:BUILD_SOURCESDIRECTORY/msgraph-sdk-raptor/msgraph-sdk-raptor-compiler-lib/appsettings.json
    displayName: 'Show app settings'
