steps:
  - pwsh: |
      if (Test-Path $(Build.SourcesDirectory)/msgraph-sdk-raptor) # multi repo checkout
      {
        $scriptPath = $(Build.SourcesDirectory)/msgraph-sdk-raptor/scripts/transformAppSettings.ps1
      }
      else # single repo checkout
      {
        $scriptPath = $(Build.SourcesDirectory)/scripts/transformAppSettings.ps1
      }
      . $scriptPath -TenantID $env:TenantID -ClientID $env:ClientID -ClientSecret $env:ClientSecret -Authority $env:Authority -Username $env:Username -Password $env:Password -RaptorStorageConnectionString $env:RaptorStorageConnectionString -EducationClientId $env:EducationClientId -EducationTenantId $env:EducationTenantId
    displayName: 'Transform app settings with the secrets'
    env:
      TenantID: $(TenantID)
      ClientID: $(ClientID)
      ClientSecret: $(ClientSecret)
      Authority: $(Authority)
      Username: $(Username)
      Password: $(Password)
      RaptorStorageConnectionString: $(RaptorStorageConnectionString)
      EducationClientId: $(EducationClientId)
      EducationTenantId: $(EducationTenantId)

  - pwsh: |
      if (Test-Path $(Build.SourcesDirectory)/msgraph-sdk-raptor) # multi repo checkout
      {
        Get-Content $env:BUILD_SOURCESDIRECTORY/msgraph-sdk-raptor/msgraph-sdk-raptor-compiler-lib/appsettings.json
      }
      else # single repo checkout
      {
        Get-Content $env:BUILD_SOURCESDIRECTORY/msgraph-sdk-raptor-compiler-lib/appsettings.json
      }
    displayName: 'Show app settings'
