namespace TestsCommon
{
    public static class GoKnownIssues
    {
        /// <summary>
        /// Gets known issues
        /// </summary>
        /// <param name="versionEnum">version to get the known issues for</param>
        /// <returns>A mapping of test names into known Go issues</returns>
        public static Dictionary<string, KnownIssue> GetGoCompilationKnownIssues()
        {
            return new Dictionary<string, KnownIssue>()
            {
                { "add-app-in-chat-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "add-app-in-team-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "add-educationcategory-to-educationassignment-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "add-member-to-group-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "add-multiple-members-to-group-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "delete-accesspackage-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "get-accesspackage-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "accesspackage-getapplicablepolicyrequirements-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "update-accesspackage-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "accesspackageassignment-filterbycurrentuser-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "accesspackageassignmentrequest-cancel-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "delete-accesspackageassignmentrequest-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "accesspackageassignmentrequest-filterbycurrentuser-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "get-accesspackageassignmentrequest-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "delete-accesspackagecatalog-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "get-accesspackagecatalog-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "update-accesspackagecatalog-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "get-accessreviewhistorydefinition-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "list-accessreviewhistoryinstance-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "accessreviewhistoryinstance-generatedownloaduri-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "accessreviewinstance-acceptrecommendations-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "accessreviewinstance-applydecisions-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "accessreviewinstance-batchrecorddecisions-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "accessreviewinstance-filterbycurrentuser-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "get-accessreviewinstance-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "accessreviewinstancedecisionitem-filterbycurrentuser-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "get-accessreviewinstancedecisionitem-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "update-accessreviewinstancedecisionitem-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "delete-accessreviewscheduledefinition-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "accessreviewscheduledefinition-filterbycurrentuser-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "get-accessreviewscheduledefinition-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "list-accessreviewinstance-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "list-accessreviewscheduledefinition-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "list-accessreviewscheduledefinition-allgroups-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "create-accessreviewscheduledefinition-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "create-accessreviewscheduledefinition-inactiveguests-m365-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "list-agreementfilelocalization-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "list-agreementfile-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "list-teamsapps-filter-distributionmethod-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "list-teamsapp-filter-id-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "list-teamsapp-filter-externalid-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "list-teamsapp-with-filter-expand-appdefinitions-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "list-teamsapp-with-bots-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "list-userconsentrequest-go-V1-compiles", NeedsAnalysisKnownIssue with {CustomMessage = "Process Timed out. Took 2m 1s" }},
                { "list-tokenissuancepolicies-on-application-go-V1-compiles", NeedsAnalysisKnownIssue with {CustomMessage = "cannot use &applicationId"}},
                { "list-tokenlifetimepolicies-on-application-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "list-bitlockerrecoverykey-filter-deviceid-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "list-accessreviewinstance-contactedreviewers-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "list-accessreviewinstancedecisionitem-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "list-agreementacceptance-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "list-approvalstage-go-V1-compiles", NeedsAnalysisKnownIssue },
                { "list-attendancerecord-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "get-b2xuserflow-list-identityproviders-go-V1-compiles", NeedsAnalysisKnownIssue with {CustomMessage = "Timed out 2m 6s"}},
                { "list-bitlockerrecoverykey-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "list-album-bundles-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "calendar-list-events-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "channel-list-member-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "get-listchannelmessages-1-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "list-tabs-in-channel-app-filter-1-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "list-tabs-in-channel-app-filter-2-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "list-channels-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "list-private-channels-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "list-installed-apps-in-chat-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "list-installed-apps-in-chat-expand-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "list-installed-apps-in-chat-expand-filter-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "list-conversation-members-1-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "list-tabs-in-chat-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "list-tabs-in-chat-app-filter-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "list-chats-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "list-chats-expand-members-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "get-listmessagereplies-1-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "list-conversation-members-2-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "group-list-drives-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "site-list-drives-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "user-list-drives-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "list-children-files-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "list-educationclass-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "group-list-permission-grants-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "list-b2xuserflows-expand-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "create-list-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "get-list-1-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "get-list-multi-expand-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "get-columns-from-list-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "enum-lists-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "create-listitem-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "get-list-item-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "get-previous-versions-listitem-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "get-list-items-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "update-listitem-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "get-single-version-listitem-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "restore-item-version-listitem-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "list-microsoftauthenticatorauthenticationmethod-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "list-organizationalbrandinglocalization-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "orgcontact-list-transitivememberof-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "get-roomlist-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "get-all-roomlists-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "update-roomlist-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "list-printconnector-2-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "list-printershare-2-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "list-printtasktrigger-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "list-group-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "list-user-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "list-printserviceendpoint-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "list-printtask-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "schedule-list-schedulinggroups-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "schedule-list-shifts-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "schedule-list-timeoffreasons-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "schedule-list-timesoff-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "list-healthoverviews-with-issues-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "list-claimsmappingpolicies-on-application-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "list-homerealmdiscoverypolicies-on-application-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "list-serviceannouncementattachment-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "list-signins-2-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "list-permission-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "list-subsites-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "list-authorednote-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "list-installed-apps-in-team-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "list-installed-teams-apps-expand-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "list-installed-apps-in-team-expand-filter-externalid-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "create-todotasklist-from-lists-go-V1-compiles", NeedsAnalysisKnownIssue with {CustomMessage = "Timed out"}},
                { "get-todotasklist-2-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "update-todotasklist-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "user-list-teamsapps-1-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "user-list-teamsapps-2-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "user-list-teamsapps-details-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "user-list-teamsapps-details-filter-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "list-windowshelloforbusinessauthenticationmethod-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "get-list-2-go-V1-compiles", NeedsAnalysisKnownIssue with {CustomMessage = "ampersand"}},
                { "list-provisioningobjectsummary-go-V1-compiles", NeedsAnalysisKnownIssue with {CustomMessage = "Timed out"}},
                { "accesspackage-filterbycurrentuser-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "accessreviewinstance-resetdecisions-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "accessreviewinstance-sendreminder-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "accessreviewinstance-stop-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "update-accessreviewinstance-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "create-accessreviewscheduledefinition-allusers-m365-aadrole-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "create-accessreviewhistorydefinition-from--go-V1-compiles", NeedsAnalysisKnownIssue},
                { "delete-activitybasedtimeoutpolicy-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "get-activitybasedtimeoutpolicy-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "create-activitybasedtimeoutpolicy-from-activitybasedtimeoutpolicies-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "update-activitybasedtimeoutpolicy-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "update-adminconsentrequestpolicy-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "delete-scopedrolemember-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "delete-administrativeunit-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "get-scopedrolemember-1-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "get-administrativeunit-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "get-scopedrolemember-2-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "post-administrativeunits-members-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "create-scopedrolemembership-from-administrativeunit-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "update-administrativeunit-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "delete-agreement-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "get-agreement-files-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "update-agreement-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "get-alert-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "update-alert-1-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "update-alert-2-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "appconsentrequest-filterbycurrentuser-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "get-appconsentrequest-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "application-addkey-1-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "application-addkey-2-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "application-addpassword-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "delete-application-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "application-delta-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "get-application-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "get-extensionproperties-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "application-get-owners-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "get-web-count-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "create-application-from-applications-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "create-call-app-hosted-media-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "create-call-service-hosted-media-1-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "create-call-service-hosted-media-2-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "create-call-service-hosted-media-3-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "create-extensionproperty-from-application-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "create-onlinemeeting-user-token-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "create-directoryobject-from-application-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "create-tokenissuancepolicy-from-application-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "create-tokenlifetimepolicy-from-application-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "application-removekey-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "application-removepassword-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "application-setverifiedpublisher-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "application-unsetverifiedpublisher-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "update-application-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "get-applicationtemplate-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "applicationtemplate-instantiate-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "approvalthis-filterbycurrentuser-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "get-approval-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "get-approvalstage-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "patch-approvalstage-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "attachment-createuploadsession-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "attachment-createuploadsession-inline-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "delete-attachment-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "get-file-attachment-v1-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "get-item-attachment-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "get-and-expand-item-attachment-go-V1-compiles", NeedsAnalysisKnownIssue with {CustomMessage = "Missing msgraphsdk.AttachmentRequestBuilderGetQueryParameters method"}},
                { "get-reference-attachment-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "update-authenticationflowspolicy-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "get-authenticationmethodspolicy-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "update-authenticationmethodspolicy-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "update-authzpolicy-guestuserlevel-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "update-authzpolicy-blockmsolpowershell-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "update-authzpolicy-applications-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "update-authzpolicy-sspr-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "update-authzpolicy-disableuserconsent-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "update-authzpolicy-enableuserconsentlow-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "delete-b2xuserflows-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "get-b2xuserflows-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "get-userflowlanguageconfiguration-2-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "get-identityuserflowattributeassignment-2-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "get-identityuserflowattributeassignment-expand-2-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "update-b2xuserflows-identityprovider-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "create-identityuserflowattributeassignment-from--2-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "get-bitlockerrecoverykey-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "get-bitlockerrecoverykey-key-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "delete-bundle-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "get-bundle-metadata-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "get-bundle-and-children-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "rename-bundle-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "calendar-getschedule-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "delete-calendar-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "get-calendarview-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "create-calendarpermissions-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "create-event-from-calendar-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "create-event-from-calendar-with-online-meeting-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "update-calendar-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "delete-calendargroup-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "get-calendargroup-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "calendargroup-get-calendars-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "create-calendar-from-calendargroup-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "update-calendargroup-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "delete-calendarpermission-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "get-calendarpermission-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "update-calendarpermission-go-V1-compiles", NeedsAnalysisKnownIssue},
                { "call-answer-go-V1-compiles", NeedsAnalysisKnownIssue}
            };
        }
    }
}
