namespace TestsCommon
{
    public static class TypeScriptKnownIssues
    {

        internal static readonly KnownIssue TypescriptMissingObjectTypeKnownIssue = new KnownIssue(Category.Documentation, GitHubIssue: "https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/813");
        internal static readonly KnownIssue TypescriptWrongFilterParameterSyntaxKnownIssue = new KnownIssue(Category.Documentation, GitHubIssue: "https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/814");
        internal static readonly KnownIssue TypescriptWrongAssignmentKnownIssue = new KnownIssue(Category.Documentation, GitHubIssue: "https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/814");
        internal static readonly KnownIssue TypescriptMissingBodyKnownIssue = new KnownIssue(Category.Documentation, GitHubIssue: "https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/814");

        /// <summary>
        /// Gets known issues
        /// </summary>
        /// <returns>A mapping of test names into known CSharp issues</returns>
        public static Dictionary<string, KnownIssue> GetTypescriptCompilationKnownIssues()
        {
            return new Dictionary<string, KnownIssue>()
            {
                {"accessreviewinstance-batchrecorddecisions-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"add-member-to-group-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"application-addkey-1-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"application-addkey-2-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"application-addpassword-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"application-removekey-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"application-removepassword-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"application-setverifiedpublisher-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"applicationtemplate-instantiate-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"attachment-createuploadsession-inline-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"attachment-createuploadsession-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"bulkaddmembers-team-partial-failure-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"bulkaddmembers-team-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"bulkaddmembers-team-upn-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"calendar-getschedule-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"call-answer-app-hosted-media-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"call-answer-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"call-cancelmediaprocessing-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"call-changescreensharingrole-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"call-logteleconferencedevicequality-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"call-mute-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"call-playprompt-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"call-recordresponse-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"call-redirect-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"call-reject-none-reason-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"call-reject-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"call-subscribetotone-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"call-transfer-1-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"call-transfer-2-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"call-transfer-3-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"call-transfer-4-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"call-transfer-5-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"call-unmute-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"call-updaterecordingstatus-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"chat-sendactivitynotification-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"chat-sendactivitynotification-upn-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"clear--presence-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"clone-team-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"contenttype-addcopy-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"contenttype-associatewithhubsites-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"contenttype-copytodefaultcontentlocation-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"conversationthread-reply-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"create-acceptedsender-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"create-claimsmappingpolicy-from-serviceprincipal-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"create-directoryobject-from-application-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"create-directoryobject-from-device-1-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"create-directoryobject-from-device-2-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"create-directoryobject-from-directoryrole-objectid-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"create-directoryobject-from-featurerolloutpolicy-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"create-directoryobject-from-serviceprincipal-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"create-educationclass-from-educationschool-5-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"create-educationuser-from-educationclass-1-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"create-educationuser-from-educationclass-2-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"create-educationuser-from-educationschool-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"create-externalsponsor-from-connectedorganization-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"create-file-attachment-with-post-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"create-group-from--typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"create-homerealmdiscoverypolicy-from-serviceprincipal-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"create-internalsponsor-from-connectedorganization-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"create-or-get-onlinemeeting-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"create-owner-from-group-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"create-reference-attachment-with-post-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"create-rejectedsenders-from-group-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"create-sectiongroup-from-sectiongroup-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"create-team-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"create-tokenissuancepolicy-from-application-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"create-tokenlifetimepolicy-from-application-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"create-user-from--typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"directoryobject-checkmembergroups-me-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"directoryobject-checkmembergroups-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"directoryobject-getavailableextensionproperties-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"directoryobject-getbyid-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"directoryobject-getmembergroups-me-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"directoryobject-getmembergroups-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"directoryobject-getmemberobjects-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"directoryobject-validateproperties-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"domain-forcedelete-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"event-accept-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"event-cancel-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"event-decline-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"event-forward-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"event-snoozereminder-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"event-tentativelyaccept-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"get-presence-multiple-users-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"group-assignlicense-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"group-removelicense-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"group-validateproperties-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"identityapiconnector-uploadclientcertificate-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"identityuserflowattributeassignment-setorder-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"mailfolder-copy-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"mailfolder-move-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"message-copy-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"message-forward-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"message-move-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"message-replyall-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"message-reply-v1-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"notebook-copynotebook-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"notebook-fromweburl-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"page-copytosection-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"participant-invite-1-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"participant-invite-2-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"participant-invite-existing-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"participant-invite-multiple-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"participant-mute-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"participant-startholdmusic-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"participant-stopholdmusic-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"permission-grant-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"post-administrativeunits-members-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"post-forward-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"post-opentypeextension-4-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"post-reply-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"printer-create-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"riskyuser-confirmcompromised-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"riskyuser-dismiss-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"schedule-put-schedulinggroups-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"schedule-share-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"section-copytonotebook-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"section-copytosectiongroup-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"serviceprincipal-addkey-1-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"serviceprincipal-addkey-2-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"serviceprincipal-addpassword-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"serviceprincipal-addtokensigningcertificate-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"serviceprincipal-removekey-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"serviceprincipal-removepassword-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"serviceupdatemessage-archive-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"serviceupdatemessage-favorite-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"serviceupdatemessage-markread-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"serviceupdatemessage-markunread-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"serviceupdatemessage-unarchive-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"serviceupdatemessage-unfavorite-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"set-presence-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"team-sendactivitynotification-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"team-sendactivitynotification-upn-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"timeoff-put-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"timeoffreason-put-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"update-accesspackageassignmentpolicy-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"update-accessreviewscheduledefinition-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"update-b2xuserflows-identityprovider-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"user-assignlicense-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"user-changepassword-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"user-checkmemberobjects-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"user-exportpersonaldata-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"user-findmeetingtimes-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"user-getmailtips-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"user-sendmail-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"user-sendmail-with-attachment-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"user-sendmail-with-headers-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"userteamwork-sendactivitynotification-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"user-translateexchangeids-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },


                {"create-agreement-from-agreements-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"create-call-app-hosted-media-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"create-call-service-hosted-media-1-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"create-call-service-hosted-media-2-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"create-call-service-hosted-media-3-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"create-chat-group-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"create-chat-oneonone-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"create-chat-oneonone-upn-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"create-claimsmappingpolicy-from-claimsmappingpolicies-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"create-conversationthread-from-conversation-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"create-event-from-calendar-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"create-event-from-calendar-with-online-meeting-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"create-event-from-group-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"create-event-from-user-multiple-locations-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"create-event-from-user-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"create-event-from-user-with-online-meeting-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"create-event-recurring-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"create-item-attachment-from-eventmessage-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"create-item-attachment-from-event-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"create-mailsearchfolder-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"create-message-from-user-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"create-messagerule-from-mailfolder-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"create-message-with-headers-from-user-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"create-namedlocation-from-conditionalaccessroot-2-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"create-permission-from--typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"create-plannertask-from-planner-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"create-prepopulated-group-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"create-role-enabled-group-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"create-team-post-minimal-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"create-team-post-upn-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"get-roleassignments-2-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"get-to-count-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"post-channelmessage-3-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"post-chatmessage-2-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"post-chatmessage-3-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"post-chatmessage-4-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"post-chatmessage-5-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"post-chatmessage-6-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"post-chatmessage-atmentionchannel-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"post-chatmessage-atmentionteam-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"post-opentypeextension-1-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"shift-get-2-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"update-authenticationmethodspolicy-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"update-contenttype-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"update-countrynamedlocation-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"update-device-extensionattributes-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"update-educationfeedbackoutcome-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"update-educationpointsoutcome-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"update-group-thread-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"update-openshift-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"update-plannerplandetails-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"update-plannertaskdetails-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"update-plannertask-typescript-V1-compiles", NeedsAnalysisKnownIssue },

            };
        }

    }
}
