namespace TestsCommon
{
    public static class TypeScriptKnownIssues
    {

        internal static readonly KnownIssue TypescriptMissingObjectTypeKnownIssue = new KnownIssue(Category.Documentation, GitHubIssue: "https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/813");
        internal static readonly KnownIssue TypescriptWrongFilterParameterSyntaxKnownIssue = new KnownIssue(Category.Documentation, GitHubIssue: "https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/814");
        internal static readonly KnownIssue TypescriptWrongAssignmentKnownIssue = new KnownIssue(Category.Documentation, GitHubIssue: "https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/814");
        internal static readonly KnownIssue TypescriptMissingBodyKnownIssue = new KnownIssue(Category.Documentation, GitHubIssue: "https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/814");
        internal static readonly KnownIssue TypescriptEnumDefaultValue = new KnownIssue(Category.Documentation, GitHubIssue: "https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/814");

        /// <summary>
        /// Gets known issues
        /// </summary>
        /// <returns>A mapping of test names into known TypeScript issues</returns>
        public static Dictionary<string, KnownIssue> GetTypeScriptCompilationKnownIssues()
        {
            return new Dictionary<string, KnownIssue>()
            {
                {"bulkaddmembers-team-partial-failure-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"bulkaddmembers-team-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"bulkaddmembers-team-upn-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"call-playprompt-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"call-recordresponse-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"call-redirect-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"call-transfer-3-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"call-transfer-4-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"conversationthread-reply-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"create-or-get-onlinemeeting-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"create-team-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"event-forward-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"group-assignlicense-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"message-forward-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"message-reply-v1-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"participant-invite-1-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"participant-invite-2-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"participant-invite-existing-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"participant-invite-multiple-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"participant-startholdmusic-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"post-forward-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"post-reply-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"schedule-put-schedulinggroups-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"timeoff-put-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"timeoffreason-put-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"update-accesspackageassignmentpolicy-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"update-accessreviewscheduledefinition-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"user-assignlicense-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"user-findmeetingtimes-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"user-sendmail-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"user-sendmail-with-attachment-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },
                {"user-sendmail-with-headers-typescript-V1-compiles", TypescriptMissingObjectTypeKnownIssue },

                {"create-message-from-mailfolder-typescript-V1-compiles", TypescriptEnumDefaultValue },
                {"update-event-typescript-V1-compiles", TypescriptEnumDefaultValue },
                {"update-message-typescript-V1-compiles", TypescriptEnumDefaultValue },
                {"update-alert-1-typescript-V1-compiles", TypescriptEnumDefaultValue },
                {"update-alert-2-typescript-V1-compiles", TypescriptEnumDefaultValue },

                {"create-agreement-from-agreements-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"create-call-app-hosted-media-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"create-call-service-hosted-media-1-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"create-call-service-hosted-media-2-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"create-call-service-hosted-media-3-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"create-chat-group-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"create-chat-oneonone-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"create-chat-oneonone-upn-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"create-claimsmappingpolicy-from-claimsmappingpolicies-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"create-conversationthread-from-conversation-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"create-event-from-calendar-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"create-event-from-calendar-with-online-meeting-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"create-event-from-group-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"create-event-from-user-multiple-locations-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"create-event-from-user-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"create-event-from-user-with-online-meeting-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"create-event-recurring-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"create-item-attachment-from-eventmessage-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"create-item-attachment-from-event-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"create-mailsearchfolder-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"create-message-from-user-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"create-messagerule-from-mailfolder-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"create-message-with-headers-from-user-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"create-namedlocation-from-conditionalaccessroot-2-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"create-permission-from--typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"create-plannertask-from-planner-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"create-prepopulated-group-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"create-role-enabled-group-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"create-team-post-minimal-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"create-team-post-upn-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"get-roleassignments-2-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"get-to-count-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"post-channelmessage-3-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"post-chatmessage-2-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"post-chatmessage-3-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"post-chatmessage-4-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"post-chatmessage-5-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"post-chatmessage-6-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"post-chatmessage-atmentionchannel-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"post-chatmessage-atmentionteam-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"post-opentypeextension-1-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"shift-get-2-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"update-authenticationmethodspolicy-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"update-contenttype-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"update-countrynamedlocation-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"update-device-extensionattributes-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"update-educationfeedbackoutcome-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"update-educationpointsoutcome-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"update-group-thread-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"update-openshift-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"update-plannerplandetails-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"update-plannertaskdetails-typescript-V1-compiles", NeedsAnalysisKnownIssue },
                {"update-plannertask-typescript-V1-compiles", NeedsAnalysisKnownIssue },

            };
        }


        /// <summary>
        /// Gets known issues
        /// </summary>
        /// <returns>A mapping of test names into known TypeScript issues</returns>
        public static Dictionary<string, KnownIssue> GetTypeScriptExecutionKnownIssues()
        {
            var executionIssues = new Dictionary<string, KnownIssue>()
            {
                {"get-organization-1-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-domains-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"user-supportedlanguages-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-bundle-metadata-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-recent-activities-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-microsoftauthenticatorauthenticationmethodconfiguration-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-windowshelloforbusinessauthenticationmethod-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-workforceintegration-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-microsoftauthenticatorauthenticationmethod-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-subjectrightsrequest-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"message-get-attachments-v1-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-owneddevices-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-callrecord-sessions-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"list-agreementfile-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-submittedresources-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-approvalstage-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-connectionoperation-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"plannerbucket-get-tasks-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-educationsubmission-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-notebooks-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-printtask-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-mailfolder-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-mailsearchfolder-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-openshift-1-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-mymodifieddocuments-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-subscription-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"list-user-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-policies-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"list-printconnector-2-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-messagerules-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-workforceintegrations-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"onenote-get-sections-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"contactfolder-get-contacts-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-hostedcontentschannelmessage-1-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-directory-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-hostedcontentschannelmessage-2-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-hostedcontentschatmessage-1-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-educationuser-1-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"contenttype-ispublished-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"list-serviceupdatemessage-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-participants-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"accesspackageassignment-filterbycurrentuser-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-drive-by-site-id-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-todotasklist-2-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-drive-default-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-riskdetection-1-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-educationuser-2-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-todotask-2-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"list-educationuser-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-printusagebyprinter-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-swapshiftschangerequest-2-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-educationassignmentresource-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-educationlinkresource-from-educationassignment-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-educationexcelresource-from-educationassignment-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-educationpowerpointresource-from-educationassignment-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-educationfileresource-from-educationassignment-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-educationmediaresource-from-educationassignment-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-outcomes-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"planner-get-tasks-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"event-get-attachments-v1-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-opentypeextension-4-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-opentypeextension-1-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-opentypeextension-2-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-rejectedsenders-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"list-printershare-2-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"list-all-bundles-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-plannertask-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-todotasklist-1-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-group-event-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-user-presences-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"post-get-attachments-v1-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-your-presence-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-participant-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-user-presence-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"list-subsites-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-classes-3-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-printconnector-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"list-printershare-1-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-userflowlanguagepage-3-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"user-get-contacts-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-buckets-1-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"timeoffreason-get-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-mailfolders-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-linkedresource-1-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-offershiftrequest-1-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-directoryaudit-1-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-licensedetails-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-mastercategories-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-linkedresource-2-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-contactfolders-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-contact-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"site-list-drives-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"callrecord-getdirectroutingcalls-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-openshiftchangerequest-2-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"list-accessreviewhistoryinstance-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-application-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"enum-drives-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"subjectrightsrequest-getfinalreport-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-serviceannouncementattachment-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-directoryaudit-2-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"notebook-get-sections-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"list-accesspackageassignmentpolicy-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-calendargroups-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-printtasktrigger-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-columns-from-list-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-listchannelmessages-1-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-registereddevices-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-schools-3-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-plannerprogresstaskboardtaskformat-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-previous-versions-listitem-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-rubrics-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"list-authorednote-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-acceptedsenders-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"list-printusagebyprinter-2-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-plans-2-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-accessreviewhistorydefinition-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-onenoteoperation-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-plannerplandetails-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"callrecord-getpstncalls-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-rubric-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-call-1-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-call-2-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-plannertaskdetails-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"sectionsgroup-get-sections-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-file-attachment-v1-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-item-attachment-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-reference-attachment-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"servicehealthissue-incidentreport-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-servicehealth-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"list-printusagebyprinter-1-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"onenote-get-sectiongroups-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"mailfolder-get-messages-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-contactfolder-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-plans-1-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-attendancereports-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-listmessagereplies-1-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-conditionalaccesspolicy-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-organization-2-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-swapshiftschangerequest-1-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-externalgroup-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-emailauthenticationmethodconfiguration-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-resources-1-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"timeoff-get-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-notebook-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-educationassignment-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-message-in-mime-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"list-printtasktrigger-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"calendargroup-get-calendars-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-entitlementmanagementsettings-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-accesspackageassignmentpolicy-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-plannerplan-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-list-1-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-list-2-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-message-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-messagerule-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"list-group-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"list-accesspackageassignmentrequest-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-submissions-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-plannerbucket-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"list-accesspackageassignment-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-shiftpreferences-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-agreementacceptances-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"user-supportedtimezones-default-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-printershare-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"schedule-list-timeoffreasons-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-plannerassignedtotaskboardtaskformat-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"list-accessreviewhistorydefinition-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"list-printservice-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-timeoffrequest-2-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-onlinemeeting-user-token-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-attendee-report-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-assignments-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"list-serviceprincipal-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-timeoffrequest-1-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"schedule-list-schedulinggroups-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"planneruser-get-tasks-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-printserviceendpoint-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-sectiongroup-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"list-printusagebyuser-1-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-userconsentrequest-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-printusagebyuser-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"sites-list-followed-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-openshiftchangerequest-1-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-calendargroup-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-user-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-chatmessagechannel-1-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-chatmessagechannel-2-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-chatmessagechannel-3-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-buckets-2-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-educationclass-members-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-section-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-educationwordresource-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-educationfileresource-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-educationexcelresource-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-educationpowerpointresource-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-educationlinkresource-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-educationmediaresource-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-serviceprincipal-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"list-application-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-domain-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-room-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-roomlist-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-educationrubric-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-calendar-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-site-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-fido2authenticationmethodconfiguration-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"list-attendancerecord-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"subjectrightsrequest-getfinalattachment-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"user-chat-teamsapps-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"list-serviceannouncementattachment-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-group-events-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-outlookcategory-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-resources-2-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"user-get-calendars-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-agreements-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-overrides-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"list-conversation-members-1-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"accesspackageassignmentrequest-filterbycurrentuser-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-teachers-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-hostedcontentchatmessage-1-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-ownedobjects-2-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"recent-notebooks-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"educationuser-delta-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"list-userconsentrequest-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"eventmessage-get-attachments-v1-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-person-collection-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"schedule-get-schedulinggroups-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"shift-get-1-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-joinedteams-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"schedule-get-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-signin-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-createdobjects-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"list-printconnector-1-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"mailfolder-get-childfolders-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"list-chats-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-all-rooms-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-all-roomlists-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-openshift-2-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"list-printusagebyuser-2-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-printoperation-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-contract-1-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-me-assignments-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-user-assignments-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-columns-from-site-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-callrecord-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-accesspackageassignmentrequest-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-sectiongroups-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"enum-lists-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-serviceupdatemessage-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-directreports-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-manager-1-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-plans-3-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-chat-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-meeting-chat-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"list-printserviceendpoint-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-appconsentrequest-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-eventmessage-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-datapolicyoperation-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-resource-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"notebook-get-sectiongroups-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-offershiftrequest-2-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-plannerbuckettaskboardtaskformat-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-printservice-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"contactfolder-get-childfolders-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"get-todotask-1-typescript-V1-executes", NeedsAnalysisKnownIssue},
                {"plannerplan-get-tasks-typescript-V1-executes", NeedsAnalysisKnownIssue},
            };

            // add all compilation known issues
            var compilationIssues = GetTypeScriptCompilationKnownIssues();
            foreach (var issuePair in compilationIssues)
            {
                if (!executionIssues.ContainsKey(issuePair.Key))
                    executionIssues.Add(issuePair.Key, issuePair.Value);
            }

            return executionIssues;
        }

    }
}
