parameters:
  projectFileName: PowerShellV1ExecutionTests
  testType: 'Execution'
steps:
- task: PowerShell@2
  displayName: Install Required Modules
  inputs:
    targetType: 'inline'
    script: |
        $module = Get-Module -Name Microsoft.Graph -ListAvailable
        if($module.Count -gt 0){
          $module[0] | %{ 
          if($_.Version -eq "1.10.0"){
          echo "Latest version already installed"
          }else{
          echo "Installing latest version"
          Install-Module Microsoft.Graph -Repository PSGallery -Scope AllUsers -Force -AllowClobber
          Import-Module Microsoft.Graph -Global -Force  
          }}
        }else{
          echo "Installing latest version"
          Install-Module Microsoft.Graph -Repository PSGallery -Scope AllUsers -Force -AllowClobber
          Import-Module Microsoft.Graph -Global -Force
        }

- template: ../common-templates/checkout.yml
- template: ../compile-run-tests-template.yml
  parameters:
    projectFileName: ${{ parameters.projectFileName }}
    runName: ${{ parameters.projectFileName }}
    testType: ${{ parameters.testType }}