# Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.

trigger: none # disable triggers based on commits.
pr: none # disable as a PR gate.
name: 'V1 PowerShell Snippet Execution Tests'

parameters:
- name: BuildAgentPool
  displayName: Build Agent Pool
  type: string
  default: 1es-MsGraphBuildAgentsWindowsRaptor

- name: PipelineTimeout
  displayName: PipelineTimeout
  type: number
  default: 600

resources:
 repositories:
   - repository: microsoft-graph-docs
     type: github
     endpoint: microsoftgraph
     name: microsoftgraph/microsoft-graph-docs
     ref: main

variables:
  buildConfiguration: 'Release'

jobs:
- job: PowerShellV1ExecutionTests
  pool: ${{ parameters.BuildAgentPool }}
  timeoutInMinutes: ${{ parameters.PipelineTimeout }}
  strategy:
    maxParallel: 1
    matrix:
        PowerShellV1ExecutionTests:
            projectFileName: PowerShellV1ExecutionTests
  steps:
  - template: powershell-execution-tests-template.yml
    parameters:
      projectFileName: $(projectFileName)
      testType: 'Execution'
