parameters:
  projectFileName: JavaV1Tests
  javaPreviewLibPath: ''
steps:
- task: PowerShell@2
  inputs:
    targetType: 'filePath'
    filePath: $(Build.SourcesDirectory)/msgraph-sdk-raptor/azure-pipelines/e2e-templates/transformSettings.ps1
    arguments: '-Version "" -KnownFailuresRequested "" -JavaPreviewLibPath $Env:JavaPreviewLibPath -Language "" -RunSettingsPath $env:RunSettingsPath'
  env:
    RunSettingsPath: '$(Build.SourcesDirectory)/$(projectFileName)/Test.runsettings'
    JavaPreviewLibPath: '$(javaPreviewLibPath)'