parameters:
  projectFileName: JavaV1Tests
  javaPreviewLibPath: ''
steps:
- task: PowerShell@2
  inputs:
    targetType: 'filePath'
    filePath: $(Build.SourcesDirectory)/msgraph-sdk-raptor/azure-pipelines/e2e-templates/transformSettings.ps1
    arguments: '-Version "" -KnownFailuresRequested "" -JavaPreviewLibPath "$(javaPreviewLibPath)" -Language "" -RunSettingsPath "$(Build.SourcesDirectory)/$(projectFileName)/Test.runsettings"'