parameters:
  projectFileName: JavaV1Tests
  javaPreviewLibPath: ''
steps:
- pwsh: $(Build.SourcesDirectory)/msgraph-sdk-raptor/azure-pipelines/e2e-templates/transformSettings.ps1 -JavaPreviewLibPath $env:JavaPreviewLibPath -Language "Java" -RunSettingsPath $env:RunSettingsPath
  env:
    RunSettingsPath: '$(Build.SourcesDirectory)/msgraph-sdk-raptor/Test.runsettings'
    JavaPreviewLibPath: ${{ parameters.javaPreviewLibPath }}
  displayName: 'Replace test settings parameters'