parameters:
  projectFileName: JavaV1Tests
  dllPath: ''
steps:
- task: PowerShell@2
  inputs:
    targetType: 'filePath'
    filePath: $(Build.SourcesDirectory)/azure-pipelines/e2e-templates/transformSettings.ps1
    arguments: '-Version "" -KnownFailuresRequested "" -DllPath "$(dllPath)" -Language "" -RunSettingsPath "$(Build.SourcesDirectory)/$(projectFileName)/Test.runsettings"'