# Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
# Steps to generate a Microsoft.Graph.dll from given metadata

steps:
- task: DotNetCoreCLI@2
  displayName: 'Build Typewriter'
  inputs:
    command: 'build'
    projects: '$(typewriterSolution)'
    arguments: '--configuration $(buildConfiguration)'

- pwsh: '$(Build.SourcesDirectory)/msgraph-sdk-raptor/scripts/generateCSharpModels.ps1'
  displayName: 'Transform metadata, run Typewriter and update models'
  env:
    BuildConfiguration: $(buildConfiguration)
    MetadataURL: $(metadataURL)

- task: PublishBuildArtifacts@1
  displayName: 'Publish metadata files as artifact'
  inputs:
   PathtoPublish: '$(Build.SourcesDirectory)/metadata'
   ArtifactName: 'metadata'
   publishLocation: 'Container'

- task: DotNetCoreCLI@2
  displayName: 'Build Microsoft.Graph.dll'
  inputs:
    command: 'build'
    projects: msgraph-sdk-dotnet/**/*.csproj
    arguments: '--configuration $(buildConfiguration)'