# Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
# Steps to generate snippets

steps:
- task: UseDotNet@2
  displayName: 'Install dotnet core SDK'
  inputs:
    version: 5.x

- task: DotNetCoreCLI@2
  displayName: 'Build snippet generator'
  inputs:
    command: 'build'
    projects: 'microsoft-graph-explorer-api/CodeSnippetsReflection.App/CodeSnippetsReflection.App.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Build apidoctor'
  inputs:
    command: 'build'
    projects: '$(apidoctorSolution)'
    arguments: '--configuration $(buildConfiguration)'

- pwsh: |
    # release folder can change based on .NET core version, so search recursively in bin folder
    $snippetGeneratorBinDirectory = Join-Path $env:BUILD_SOURCESDIRECTORY/microsoft-graph-explorer-api/CodeSnippetsReflection.App/bin $(buildConfiguration)
    $snippetGeneratorPath = (Get-ChildItem $snippetGeneratorBinDirectory *App.exe -Recurse).FullName
    Write-Host "Path to snippet generator tool: $snippetGeneratorPath"

    $apidoctorBinDirectory = Join-Path $env:BUILD_SOURCESDIRECTORY/apidoctor/ApiDoctor.Console/bin $(buildConfiguration)
    $apidoctorPath = (Get-ChildItem $apidoctorBinDirectory apidoc.exe -Recurse).FullName
    Write-Host "Path to apidoctor tool: $apidoctorPath"

    $apidoctorPath generate-snippets --ignore-warnings --path . --snippet-generator-path $snippetGeneratorPath --lang $(snippetLanguages) --git-path "C:/Program Files/Git/bin/git.exe" --custom-metadata-path $(Build.SourcesDirectory)/metadata/metadata.xml
  displayName: 'Generate snippets'
  workingDirectory: microsoft-graph-docs