name: "create reports"

on:
  push:
    branches-ignore:
      - 'dev'
      - 'main'
    paths:
      - '.github/workflows/create-reports.yml'
      - 'TestsCommon/**/*.*'
      - 'ReportGenerator/**/*.*'

jobs:
  create-reports:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.5
      with:
        repository: microsoftgraph/microsoft-graph-docs
        path: microsoft-graph-docs
        persist-credentials: false
    - uses: actions/checkout@v2.3.5
      with:
        path: msgraph-sdk-raptor
        persist-credentials: false
    - name: Setup .NET
      uses: actions/setup-dotnet@v1.8.2
      with:
        dotnet-version: 6.0.x
    - name: set environment variables
      run: |
        $branchName = $Env:GITHUB_REF.replace("refs/heads/", "")
        echo "CURRENT_BRANCH=${branchName}" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append

        $sourcesDirectory = $Env:GITHUB_WORKSPACE
        echo "BUILD_SOURCESDIRECTORY=${sourcesDirectory}" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
      shell: pwsh
    - name: Create reports
      run: |
        dotnet run --project ./ReportGenerator/ReportGenerator.csproj
      shell: pwsh
      working-directory: msgraph-sdk-raptor
      env:
        RAPTOR_CONFIGCONNECTIONSTRING : ${{ secrets.RAPTOR_CONFIGCONNECTIONSTRING }}
    - name: push reports
      uses: actions-x/commit@v4
      with:
        directory: '/home/runner/work/msgraph-sdk-raptor/msgraph-sdk-raptor/msgraph-sdk-raptor' # multi-repo checkout requires this
        token: ${{ secrets.PAT }}
        branch: ${{ env.CURRENT_BRANCH }}
        message: 'Update reports'
        force: 'true'
        name: 'Mustafa Zengin'
        email: 'muzengin@microsoft.com'
