name: "create reports"

on:
  push:
    branches-ignore:
      - 'dev'
      - 'main'
    paths:
      - '.github/workflows/create-reports.yml'
      - 'TestsCommon/**/*.*'
      - 'ReportGenerator/**/*.*'

jobs:
  create-reports:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.5
      with:
        repository: microsoftgraph/microsoft-graph-docs
        path: microsoft-graph-docs
    - uses: actions/checkout@v2.3.5
      with:
        path: msgraph-sdk-raptor
    - name: Setup .NET
      uses: actions/setup-dotnet@v1.8.2
      with:
        dotnet-version: 6.0.x
    - name: set environment variables
      run: |
        $branchName = $Env:GITHUB_REF.replace("refs/heads/", "")
        echo "CURRENT_BRANCH=${branchName}" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append

        $sourcesDirectory = $Env:GITHUB_WORKSPACE
        echo "BUILD_SOURCESDIRECTORY=${sourcesDirectory}" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
      shell: pwsh
    - name: Create reports
      run: |
        dotnet run -p ./ReportGenerator/ReportGenerator.csproj
      shell: pwsh
      working-directory: ${{ env.BUILD_SOURCESDIRECTORY }}/msgraph-sdk-raptor
      env:
        RAPTOR_CONFIGCONNECTIONSTRING : ${{ secrets.RAPTOR_CONFIGCONNECTIONSTRING }}

    - name: push reports
      run: |
        Write-Host "Pushing reports to $env:CURRENT_BRANCH branch"
        git config --global user.email "GraphTooling@service.microsoft.com"
        git config --global user.name "Microsoft Graph DevX Tooling"
        git add report/
        git commit -m "Update reports"
        git push origin $env:CURRENT_BRANCH
      shell: pwsh
      working-directory: ${{ env.BUILD_SOURCESDIRECTORY }}/msgraph-sdk-raptor
      env:
        CURRENT_BRANCH: ${{ env.CURRENT_BRANCH }}