# Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.

trigger: none # disable triggers based on commits.
pr: none # disable this as a PR check
name: 'Weekly Delegated App Creator'

schedules:
  - cron: "0 3 * * SAT" # every Saturday at 3AM UTC (off hours for Redmond, Nairobi and Montréal)
    displayName: 'Weekly Delegated App Creator'
    branches:
      include:
      - dev
    always: true

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- checkout: self
  clean: true
  fetchDepth: 1
- template: common-templates/transform-app-settings.yml
- template: common-templates/use-dotnet-sdk.yml
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/DelegatedAppCreator.csproj'
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'Build DelegatedAppCreator'

# not using dotnet run due to the following issue preventing us from picking up appsettings.json file
# consistently between VS and dotnet command line: https://github.com/dotnet/project-system/issues/3619
- pwsh: |
    chmod +x ./DelegatedAppCreator
    ./DelegatedAppCreator
  workingDirectory: '$(Build.SourcesDirectory)/DelegatedAppCreator/bin/Release/net5.0'
  displayName: 'Create delegated apps'
