# Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.

trigger: none # disable triggers based on commits.
pr:
  branches:
    include:
      - dev
      - main
  paths:
    include:
      - azure-pipelines/java*
      - Java*
      - java-dependencies/*
      - TestsCommon/JavaTestRunner.cs
      - TestsCommon/JavaKnownIssues.cs
schedules:
  - cron: "0 3 * * *" # everyday at 3AM UTC (off hours for Redmond, Nairobi and Montréal)
    displayName: 'Daily V1 Java Snippet Compilation Tests'
    branches:
      include:
      - dev
    always: true

name: 'V1 Java Snippet Compilation Tests'

resources:
 repositories:
   - repository: microsoft-graph-docs
     type: github
     endpoint: microsoftgraph
     name: microsoftgraph/microsoft-graph-docs
     ref: main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- template: java-templates/java-prepare.yml
- template: common-templates/checkout.yml
- template: java-templates/java-replace-local-path.yml
  parameters:
    projectFileName: JavaV1Tests
    javaPreviewLibPath: ''
- template: compile-run-tests-template.yml
  parameters:
    projectFileName: JavaV1Tests
    runName: 'V1 Java Snippet Compilation Tests $(testRunTitle)'
