# Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.

trigger: none # disable triggers based on commits.
pr: none # disable this as a PR check
name: 'Daily V1 C# Snippet Execution Tests - Known Issues'

schedules:
  - cron: "0 3 * * *" # everyday at 3AM UTC (off hours for Redmond, Nairobi and Montréal)
    displayName: 'Daily PROD V1 Execution Pipeline - Known Issues'
    branches:
      include:
      - dev
    always: true

resources:
 repositories:
   - repository: microsoft-graph-docs
     type: github
     endpoint: microsoftgraph
     name: microsoftgraph/microsoft-graph-docs
     ref: main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- template: common-templates/checkout.yml
- template: common-templates/transform-app-settings.yml
- template: compile-run-tests-template.yml
  parameters:
    projectFileName: CsharpV1ExecutionKnownFailureTests
    runName: 'Weekly V1 C# Snippet Execution Tests - Known Issues'
    testType: 'Execution'